### Numpy

In [1]:
import numpy as np

In [2]:
#checking numpy version
print(np.__version__)

1.20.1


In [3]:
#creating a numpy array

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#use a tuple to create a numpy array

import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


Task

In [6]:
print(np.__version__)

1.20.1


In [7]:
#list
import numpy as np
data_list = np.array(['kucing', 'kelinci', 'merpati'])
print(data_list)

['kucing' 'kelinci' 'merpati']


In [8]:
#tuple
import numpy as np
data_tuple = np.array(('kucing', 'kelinci', 'merpati'))
print(data_tuple)

['kucing' 'kelinci' 'merpati']


#### Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

In [9]:
# 0-D Array
import numpy as np
arr = np.array(42)
print(arr)

42


In [10]:
# 1-D Array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [11]:
# 2-D Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
#create a 3-D array with two 2-D arrays, both containing two arrays
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Task

In [13]:
# 0-D Array
import numpy as np
arr = np.array('Kucing')
print(arr)

Kucing


In [14]:
# 1-D Array
import numpy as np
arr = np.array(['kucing11', 'kucing12', 'kucing13'])
print(arr)

['kucing11' 'kucing12' 'kucing13']


In [15]:
# 2-D Array
import numpy as np
arr = np.array([['kucing11', 'kucing12', 'kucing13'],
                ['kucing21', 'kucing22', 'kucing23']])
print(arr)

[['kucing11' 'kucing12' 'kucing13']
 ['kucing21' 'kucing22' 'kucing23']]


In [16]:
# 3-D Array
import numpy as np
arr = np.array([[['kucing11', 'kucing12', 'kucing13'], 
                 ['kucing21', 'kucing22', 'kucing23'], 
                 ['kucing31', 'kucing32', 'kucing33']]])
print(arr)

[[['kucing11' 'kucing12' 'kucing13']
  ['kucing21' 'kucing22' 'kucing23']
  ['kucing31' 'kucing32' 'kucing33']]]


#### Check How Many Dimensions the Arrays Have

In [17]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
#create an array with 5 dimensions and verify that it has 5 dimensions

import numpy as np

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('number of dimension:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension: 5


Task

In [21]:
import numpy as np

z = np.array(0)
a = np.array([1,1,1])
b = np.array([[1,1,1],
              [2,2,2]])
c = np.array([[[1,1,1],
               [2,2,2],
               [3,3,3]]])
d = np.array([[[[1,1,1],
                [2,2,2],
                [3,3,3],
                [4,4,4]]]])
e = np.array([[[[[1,1,1],
                 [2,2,2],
                 [3,3,3],
                 [4,4,4],
                 [5,5,5,]]]]])

print(z.ndim)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4
5


In [22]:
import numpy as np

arr = np.array(['kucing'], ndmin=5)

print(arr)
print('number of dimension:', arr.ndim)

[[[[['kucing']]]]]
number of dimension: 5


#### Get the Element from Array

In [23]:
# Get the first element from the following array
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])

1


In [24]:
# Get the second element from the following array
import numpy as np
arr = np.array([1,2,3,4])
print(arr[1])

2


In [27]:
# Get the third and fourth element from the following array
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


Task

In [32]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [35]:
# 2p
print(arr[0:3])

[1 2 3]


In [38]:
# 3p
print(arr[0:8:2])

[1 3 5 7]


In [39]:
# operasi index
print(arr[2] + arr[3])

7


In [37]:
# operasi index
print(arr[0:2] + arr[1:3])

[3 5]


In [40]:
print( arr[2], 'dan', arr[3])

3 dan 4


#### Access the Element Based on Row/Column

In [54]:
# Access the element on the first row, second column
import numpy as np
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  2


In [56]:
# Access the element on the second row, third column
import numpy as np
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])
print('3rd element on 2nd row: ', arr[1,2])

3rd element on 2nd row:  8


In [57]:
# Access the element on the 2nd row, 5th column
import numpy as np
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1,4])

5th element on 2nd row:  10


In [44]:
# Access the third element of the second
import numpy as np
arr = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]])
print(arr[0,1,2])

6


In [51]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[1,0,2])

9


Task

In [100]:
import numpy as np
arr = np.array([[[1,2,3,4,5], 
                 ['enam', 'tujuh', 'delapan','sembilan','sepuluh'],
                 [11,12,13,14,15]]])

In [101]:
# 1p
print('elements on 1st row: ', arr[0])

elements on 1st row:  [['1' '2' '3' '4' '5']
 ['enam' 'tujuh' 'delapan' 'sembilan' 'sepuluh']
 ['11' '12' '13' '14' '15']]


In [102]:
# 2p
print('3rd element on 1st row: ', arr[0:2])

3rd element on 1st row:  [[['1' '2' '3' '4' '5']
  ['enam' 'tujuh' 'delapan' 'sembilan' 'sepuluh']
  ['11' '12' '13' '14' '15']]]


In [103]:
# 3p
print(' 2nd element on the 1st row, 3th column: ', arr[0,2,1])

 2nd element on the 1st row, 3th column:  12


Print the last element from the 2nd dim

In [81]:
import numpy as np
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])
print('last elements from 2nd dim: ', arr[1,-1])

last elements from 2nd dim:  10


#### Slice Elements from Index from the Following Array

In [83]:
# Slice elements from index 5 from the following array
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [104]:
# Slice elements from index 4 to thr end of the array
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [105]:
# Slice elements from the beginning to index 4 (not included)
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [106]:
# Slice elements from the index 3 to index 1 from the end
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


Task

#### Use the Step Value to Determine the Step of the Slicing

In [91]:
#
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [92]:
#from both element, return index 2
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 2])

[3 8]


In [107]:
#from both element, slice index 1 to index 4 (not included), this will return a 2-d array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


Task

In [108]:
import numpy as np
arr = np.array([[['kucing11', 'kucing12', 'kucing13'], 
                 ['kucing21', 'kucing22', 'kucing23'], 
                 ['kucing31', 'kucing32', 'kucing33']]])
print(arr)

[[['kucing11' 'kucing12' 'kucing13']
  ['kucing21' 'kucing22' 'kucing23']
  ['kucing31' 'kucing32' 'kucing33']]]


In [116]:
# 1p, 2p
print(arr[0, 0:2])

[['kucing11' 'kucing12' 'kucing13']
 ['kucing21' 'kucing22' 'kucing23']]


In [118]:
# 2p, 1p
print(arr[0:2, 1])

[['kucing21' 'kucing22' 'kucing23']]


In [113]:
# 2p, 2p
print(arr[0:2, 1:3])

[[['kucing21' 'kucing22' 'kucing23']
  ['kucing31' 'kucing32' 'kucing33']]]


#### Get Data of the Object

In [96]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [97]:
#### Change data type from float to integer by using 'i' as parameter value


In [ ]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])